### ISSUE TITLE
Input not being updated

### ISSUE THREAD

**Issue by threeaccents** [MadimetjaShika/vuetify-google-autocomplete#51] opened 2018-07-14 16:24 UTC
Once an address is selected the input doesn't update with the full address.

Here is my component

```javascript
<vuetify-google-autocomplete ref="address" id="map" append-icon="search" placeholder="Address" v-on:placechanged="getAddressData">
</vuetify-google-autocomplete>
```

```javascript
getAddressData(addressData, placeResultData, id) {
      if (placeResultData) {
        this.address = placeResultData.formatted_address;
      }
    },
```

If I start typing let's say `15565` and the address list pops up and I select an address the function gets called the address variable gets set but in the UI the input doesn't update with the full address it just stays `15565`

**Comment by MadimetjaShika** [comment] 2018-07-26 12:36
Hi @threeaccents,

That behaviour is odd and shouldn't be happening. I'm struggling to reproduce this though. Which version of the library are you using?

Can you please also share a screenshot of how the input looks after you've selected an address?

**Comment by nkostic** [comment] 2018-08-29 08:53
Hi,
I have the same issue with 1.1.0. Tried Chrome PC and Mac.
See the behaviour in this example video : https://drive.google.com/file/d/1lea7q-lIzYRsOXTXPkWfFV9wB9y-wSVc/view
Also attached is the screenshot photo
![step1](https://user-images.githubusercontent.com/426266/44777011-ba7ae500-ab36-11e8-912e-0fb52c46a012.png)

![step2](https://user-images.githubusercontent.com/426266/44777019-bf3f9900-ab36-11e8-951f-8d2e14af3bc2.png)
.

**Comment by nkostic** [comment] 2018-08-29 08:59
Tried also the 2.0.0-beta.4 and it seems like that issue is not present there but I have different issue.  Only when I reload the page plugin works, after I switch page (using vue router) plugin stops working until manual reload of the page occures.

**Comment by MadimetjaShika** [comment] 2018-09-16 15:20
Hi Guys,

@nkostic - I've explained the issue behind the library not working after a vue-router page navigation in issue #56, you can read there for an explanation. However this has now been resolved, and should be okay in the next release.

@threeaccents I still cannot reproduce the issue you mentioned with the input not updating (with ``v2.0.0-beta.4``), see attached gif.

![vga-input-not-updating- 51-1](https://user-images.githubusercontent.com/6643245/45598086-1d44fb00-b9d6-11e8-814e-51232ea4834b.gif)

I will close this issue once I've published the new release. Please do let me know if any of these issues are still not resolved.

**Closed as completed** 2018-09-16 16:03 UTC
