### ISSUE TITLE
Using vuetify-google-autocomplete with vue-google-maps

### ISSUE THREAD

**Issue by jondewoo** [MadimetjaShika/vuetify-google-autocomplete#29] opened 2018-03-07 13:25 UTC
Hi @MadimetjaShika,

I'm building a Vue component using vuetify-google-autocomplete and [vue-google-maps](https://github.com/xkjyeah/vue-google-maps).
It seems I'm running into trouble as both access the Google Maps API as you suspected in #16:
> As noted on the release notes, you might still experience issues if you try to use this component with a different vue component that also loads the Google API. I haven't yet built to cater for that.

I tried using `:load-google-api` as mentioned in the release notes, without success.

Do you have plans in the near future to make such an integration possible? If not, do you know if there is a workaround?

**Edit:**
To give you a bit more information and context, the app is using vue-router.
vue-google-maps is initialized globally (`Vue.use(...)` in main.js) while vuetify-google-autocomplete is initialized locally as a component.
I've noticed that when navigating (using vue-router) from a page that does not include vuetify-google-autocomplete to a page that includes it makes it work properly. Accessing the page directly causes vuetify-google-autocomplete to fail silently. In both cases, vue-google-maps works properly.

Thanks,
Jonathan

**Comment by MadimetjaShika** [comment] 2018-03-10 09:29
Hi @jderrough 

Thanks for posting the issue, i'll look into this sometime this weekend and let you know when it's all sorted. I think I have an idea of what might be causing this.

**Comment by MadimetjaShika** [comment] 2018-03-18 09:50
Hi @jderrough 

Regarding the route-change issue, it has been noted in #26 and should now be fixed as of ``2.0.0-Alpha.7``.

As for the issue regarding using multiple libraries that depend on the Google Maps SDK, I am still looking into this and trying to figure out how to elegantly and effectively get around this. A simple fix I thought of was to rely on the consumer/parent to "_synchronously_" load the Google SDK,  which  would work. However the underlying problem still remains because the other library still injects the Google SDK script into the DOM, which causes the ``You have included the Google Maps API multiple times on this page. This may cause unexpected errors.`` error.

Another solution would be to tell this component not to load the Google SDK, and somehow synchronously wait for the other component to load the SDK (and get notified when that has happened). I am currently trying to see how I can get this to work.

Please do shout if you have any suggestions or alternate solutions.

**Comment by gabaum10** [comment] 2018-04-26 14:14
This is causing issues for me as well.  I'm seeing all sorts of load errors and weird behaviors.  Is there a way to detect if the API has already been loaded and not include it?

**Comment by gabaum10** [comment] 2018-04-26 14:17
As mentioned in the original issue, It looks like there is already a prop called `loadGoogleApi`, but it doesn't seem to do anything.

**Comment by gabaum10** [comment] 2018-04-26 18:17
@MadimetjaShika I submitted a pull request with a fix to prevent google from being loaded multiple times.

**Closed as completed** 2018-04-27 20:04 UTC
Labels: bug, enhancement

**Comment by MadimetjaShika** [comment] 2018-04-27 20:09
@gabaum10 thanks for the PR, i've tested and it seems to be working as intended, nice one!

@jderrough please just confirm if this works for your scenario as well. The fix is published from version ``2.0.0-Alpha.9``

**Comment by jvb93** [comment] 2018-06-24 20:45
@gabaum10 @MadimetjaShika Hey guys, I'm on 2.0.0-beta.4, also using vue-google-maps with this library and am still getting `You have included the Google Maps JavaScript API multiple times on this page. This may cause unexpected errors.`

Am I missing something?

**Comment by jondewoo** [comment] 2018-10-13 10:41
Hi @MadimetjaShika,

I'm now using the 2.0.0-beta.5, and autocomplete still doesn't work when accessing or refreshing the page using the component. Same context as before, I'm using Google Maps along with this component. I'll try to investigate in the coming weeks.

**Comment by romucci** [comment] 2018-10-31 01:32
I am still having issues setting vuetify-google-autocomplete when I am also using vue2-google-maps, I only use the API key when I load google maps and it used to kind of work, but now it gives me certain errors like .

```
VuetifyGoogleAutocomplete.js?2bd5:330 Uncaught TypeError: Cannot read property 'setBounds' of null
```

**Comment by andreav** [comment] 2018-11-20 23:21
Same here (beta-5 me too). Did anyone find a solution?

**Comment by irriss** [comment] 2019-05-21 03:41
The problem still exists. Not sure why the issue is closed.

**Comment by mrKoujou** [comment] 2019-05-21 14:05
Hi, guys. If you are using vuetify-google-autocomplete with vue2-google-maps and having problem described above, this can help you. I'm using Vue CLI 3 and install this two modules as plugins and all I needed to do is manually load google api using vue2-google-maps (in vue2-google-maps plugin, see below) and remove api-key from vuetify-google-autocomplete plugin. vue2-google-maps should be loaded first (in main.js).

plugins/vue2-google-maps.js
`import Vue from 'vue';
import * as VueGoogleMaps from 'vue2-google-maps';

Vue.use(VueGoogleMaps, {
load: {
  key: process.env.VUE_APP_GEOAPI_KEY,
  libraries: 'places,drawing,visualization',
},
});

**Vue.$gmapApiPromiseLazy();**
`

plugins/vuetify-google-autocomplete.js
`import Vue from 'vue';
import VuetifyGoogleAutocomplete from 'vuetify-google-autocomplete';

Vue.use(VuetifyGoogleAutocomplete, {});
`
